In [1]:
import pandas as pd
import torch

In [2]:
dat = pd.read_csv("train.csv")
datt = pd.read_csv("test.csv")

In [3]:
dat.describe()

id      feature_0      feature_1      feature_2  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean    99999.500000       0.972710       1.168365       2.219325   
std     57735.171256       3.941836       3.993407       6.476570   
min         0.000000       0.000000       0.000000       0.000000   
25%     49999.750000       0.000000       0.000000       0.000000   
50%     99999.500000       0.000000       0.000000       0.000000   
75%    149999.250000       1.000000       1.000000       1.000000   
max    199999.000000      61.000000      51.000000      64.000000   

           feature_3      feature_4      feature_5      feature_6  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean        2.296735       0.793530       1.431105       1.010695   
std         7.551858       2.935785       5.162746       3.949231   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         1.000000       0.000000       1.000000       0.000000   
max        70.000000      38.000000      76.000000      43.000000   

           feature_7     feature_8  ...     feature_65     feature_66  \
count  200000.000000  200000.00000  ...  200000.000000  200000.000000   
mean        0.673090       1.94398  ...       1.798040       0.508695   
std         2.234949       3.93133  ...       5.053014       1.867330   
min         0.000000       0.00000  ...       0.000000       0.000000   
25%         0.000000       0.00000  ...       0.000000       0.000000   
50%         0.000000       0.00000  ...       0.000000       0.000000   
75%         0.000000       2.00000  ...       1.000000       0.000000   
max        30.000000      38.00000  ...      54.000000      24.000000   

          feature_67     feature_68     feature_69     feature_70  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean        1.827300       0.910370       1.603585       1.219210   
std         7.188924       3.835182       4.877679       4.826003   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         1.000000       1.000000       2.000000       1.000000   
max        79.000000      55.000000      65.000000      67.000000   

          feature_71     feature_72    feature_73     feature_74  
count  200000.000000  200000.000000  200000.00000  200000.000000  
mean        0.806895       1.282925       2.94021       0.632005  
std         2.458741       4.261420      10.78465       3.925310  
min         0.000000       0.000000       0.00000       0.000000  
25%         0.000000       0.000000       0.00000       0.000000  
50%         0.000000       0.000000       0.00000       0.000000  
75%         1.000000       1.000000       1.00000       0.000000  
max        30.000000      61.000000     130.00000      52.000000  

[8 rows x 76 columns]

In [4]:
dat1 = dat.copy()
datt1 = datt.copy()

In [5]:
dat1.columns[:2], datt1.columns[:2]

(Index(['id', 'feature_0'], dtype='object'),
 Index(['id', 'feature_0'], dtype='object'))

In [6]:
dat1.target[:3]

0    Class_6
1    Class_6
2    Class_2
Name: target, dtype: object

In [7]:
dat1.target.value_counts()

Class_6    51811
Class_8    51763
Class_9    25542
Class_2    24431
Class_3    14798
Class_7    14769
Class_1     9118
Class_4     4704
Class_5     3064
Name: target, dtype: int64

In [8]:
print(dat1.feature_1.value_counts().keys().sort_values()) 
dat1.feature_1.value_counts().size

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 30, 31, 35, 36, 37, 38,
            39, 41, 51],
           dtype='int64')


37

In [9]:
word = "Class_{}"
lisp = [word.format(i) for i in range(1,10)]
lisf = [i for i in range(1,10)]
dat1.target.replace(lisp,lisf,inplace=True)

In [10]:
dat1.target.value_counts()

6    51811
8    51763
9    25542
2    24431
3    14798
7    14769
1     9118
4     4704
5     3064
Name: target, dtype: int64

In [11]:
iden = datt1.id.copy()
dat1.drop(axis = 1, labels = 'id', inplace = True)
datt1.drop(axis = 1, labels = 'id', inplace = True)

In [12]:
dat1[:].head(), datt1.head()

(   feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
 0          0          0          6          1          0          0   
 1          0          0          0          0          0          0   
 2          0          0          0          0          0          1   
 3          0          0          7          0          1          5   
 4          1          0          0          0          0          0   
 
    feature_6  feature_7  feature_8  feature_9  ...  feature_66  feature_67  \
 0          0          0          7          0  ...           0           0   
 1          0          0          0          0  ...           2           0   
 2          0          3          0          0  ...           0           0   
 3          2          2          0          1  ...           0           4   
 4          0          0          0          0  ...           0           0   
 
    feature_68  feature_69  feature_70  feature_71  feature_72  feature_73  \
 0          

In [13]:
col = [str(i) for i in range(0,75)]
datt1.columns = col
col.append('target')
dat1.columns = col
col.pop(-1)

'target'

In [14]:
dat1.columns[:5], datt1.columns[:5]

(Index(['0', '1', '2', '3', '4'], dtype='object'),
 Index(['0', '1', '2', '3', '4'], dtype='object'))

In [15]:
'''dat2 = dat1.copy()
for i in range(0,74):
    for j in range(i+1,75):
        dat2[f"{i}{j}"] = dat2[f"{i}"]*dat2[f"{j}"]
        print(f"{i}{j}")
dat2.columns'''

'dat2 = dat1.copy()\nfor i in range(0,74):\n    for j in range(i+1,75):\n        dat2[f"{i}{j}"] = dat2[f"{i}"]*dat2[f"{j}"]\n        print(f"{i}{j}")\ndat2.columns'

In [16]:
'''for i in range(0,75):
    dat2[f"{i}{i}"] = dat2[f"{i}"]*dat2[f"{i}"]
    print(f"{i}{i}")
dat2.columns'''

'for i in range(0,75):\n    dat2[f"{i}{i}"] = dat2[f"{i}"]*dat2[f"{i}"]\n    print(f"{i}{i}")\ndat2.columns'

In [17]:
#corrmat = dat1[col].corr()

In [18]:
#for i in range(75):
#    print(corrmat[corrmat[f'{i}']>0.5][f'{i}'])

In [19]:
#len(dat2.columns)

In [20]:
#dat2 = dat2/dat2.max()
#dat2.head()

In [21]:
dat1[col] = dat1[col]/dat1[col].max()

In [22]:
#dat1 = dat2.copy()

In [23]:
#dat1 = 0

In [24]:
dat1.sample(frac=1)
split = 160000
#train = dat2[:split]
#test = dat2[split:]
x = dat1[:split][col]
y = dat1[:split].target
xt = dat1[split:][col]
yt = dat1[split:].target
print(x.shape, xt.shape)
y.head(), yt.head()

(160000, 75) (40000, 75)


(0    6
 1    6
 2    2
 3    8
 4    2
 Name: target, dtype: int64,
 160000    1
 160001    6
 160002    3
 160003    2
 160004    2
 Name: target, dtype: int64)

In [25]:
'''mytry = dat1[dat1['0'] > 0].copy()
mytry = mytry[mytry['target'] == 7]
print(mytry['0'].value_counts())
mytry = dat1[dat1['1'] > 0].copy()
print(mytry.target.value_counts())
for i in range(2,75):
    feat = "{}"
    mytry = dat1[dat1[f"{i}"] == 0].copy()
    print(mytry.target.value_counts())'''

'mytry = dat1[dat1[\'0\'] > 0].copy()\nmytry = mytry[mytry[\'target\'] == 7]\nprint(mytry[\'0\'].value_counts())\nmytry = dat1[dat1[\'1\'] > 0].copy()\nprint(mytry.target.value_counts())\nfor i in range(2,75):\n    feat = "{}"\n    mytry = dat1[dat1[f"{i}"] == 0].copy()\n    print(mytry.target.value_counts())'

In [26]:
'''mytry = dat[dat['feature_0'] == 0].copy()
print(mytry.target.value_counts())
mytry = dat[dat['feature_1'] == 0].copy()
print(mytry.target.value_counts())
for i in range(2,75):
    feat = "feature_{}"
    mytry = dat[dat[f"feature_{i}"] == 0].copy()
    print(mytry.target.value_counts())'''

'mytry = dat[dat[\'feature_0\'] == 0].copy()\nprint(mytry.target.value_counts())\nmytry = dat[dat[\'feature_1\'] == 0].copy()\nprint(mytry.target.value_counts())\nfor i in range(2,75):\n    feat = "feature_{}"\n    mytry = dat[dat[f"feature_{i}"] == 0].copy()\n    print(mytry.target.value_counts())'

In [27]:
import numpy as np

train_x = torch.tensor(x.values.astype(np.float32))
#train_x.add_(1)
train_y = torch.tensor(y.values.astype(np.int64))
train_y.add_(-1)
#train_y = torch.nn.functional.one_hot(train_y)
train_x[0], train_y[0]

(tensor([0.0000, 0.0000, 0.0938, 0.0143, 0.0000, 0.0000, 0.0000, 0.0000, 0.1842,
         0.0000, 0.0000, 0.0000, 0.0811, 0.0000, 0.0312, 0.0000, 0.0000, 0.2143,
         0.1364, 0.0038, 0.0000, 0.0606, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0095, 0.0000, 0.0000, 0.0256, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.3235, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1429, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0536, 0.0000, 0.0263, 0.0833,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0125, 0.0098,
         0.0000, 0.0000, 0.0556, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0328, 0.0000, 0.0000]),
 tensor(5))

In [28]:
test_x = torch.tensor(xt.values.astype(np.float32))
#test_x.add_(1)
test_y = torch.tensor(yt.values.astype(np.int64))
test_y.add_(-1)
#test_y = torch.nn.functional.one_hot(test_y)
test_x[0], test_y[0]

(tensor([0.0000, 0.0196, 0.2031, 0.1143, 0.0000, 0.0658, 0.0233, 0.0000, 0.0526,
         0.0000, 0.0303, 0.0000, 0.0000, 0.0000, 0.0312, 0.0000, 0.0000, 0.0000,
         0.3182, 0.0000, 0.0333, 0.0000, 0.0000, 0.1818, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0256, 0.0641, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0294, 0.0000, 0.1224, 0.0000, 0.0274, 0.0000, 0.0159, 0.0741,
         0.0000, 0.0000, 0.0309, 0.0000, 0.1316, 0.0000, 0.0137, 0.0526, 0.0278,
         0.0000, 0.0000, 0.0652, 0.0000, 0.0333, 0.0028, 0.0043, 0.0250, 0.0588,
         0.0000, 0.2800, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0667,
         0.0656, 0.3154, 0.0577]),
 tensor(0))

In [30]:
from torch.utils.data import Dataset
class mydataset(Dataset):
    def __init__(self, data, labels):
        self.labels = labels
        self.data = data
    def __len__(self):
        return len(self.labels)
    def __getitem__(self,idx):
        item = self.data[idx]
        #label = torch.nn.functional.one_hot(self.labels[idx],num_classes=9)
        label = self.labels[idx]
        return (item,label)
training_data = mydataset(train_x,train_y)
testing_data = mydataset(test_x,test_y)
training_data, testing_data, next(iter(training_data)), training_data[0]

(<__main__.mydataset at 0x16991a889d0>,
 (tensor([0.0000, 0.0000, 0.0938, 0.0143, 0.0000, 0.0000, 0.0000, 0.0000, 0.1842,
          0.0000, 0.0000, 0.0000, 0.0811, 0.0000, 0.0312, 0.0000, 0.0000, 0.2143,
          0.1364, 0.0038, 0.0000, 0.0606, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0095, 0.0000, 0.0000, 0.0256, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.3235, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1429, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0536, 0.0000, 0.0263, 0.0833,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0125, 0.0098,
          0.0000, 0.0000, 0.0556, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0328, 0.0000, 0.0000]),
  tensor(5)),
 (tensor([0.0000, 0.0000, 0.0938, 0.0143, 0.0000, 0.0000, 0.0000, 0.0000, 0.1842,
          0.0000, 0.0000, 0.0000, 0.0811, 0.0000, 0.0312, 0.0000, 0.0000, 0.2143,
          0.1364, 0.0038, 0.0000, 0.0606, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        

In [22]:
from torch.utils.data import DataLoader
train_dataloader = DataLoader(training_data, batch_size = 100, shuffle = True)
test_dataloader = DataLoader(testing_data, batch_size = 100, shuffle = True)

In [75]:
'''from torch import nn

class myloss(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,x,y):
        l1 = len(x)
        l = len(x[0])
        s = ((-1)*sum(y[0]*torch.log(x[0]) + (1-y[0])*(torch.log(1-x[0])))/l).clone()
        for X,Y in zip(x,y):
            s += ((-1)*sum(Y*torch.log(X) + (1-Y)*(torch.log(1-X)))/l).clone()
        s = s/l1
        return s
a = myloss()
a([torch.tensor([.3,.3,.3]),torch.tensor([.3,.3,.3])],[torch.tensor([0,0,1]),torch.tensor([0,0,1])])'''

'from torch import nn\n\nclass myloss(nn.Module):\n    def __init__(self):\n        super().__init__()\n    def forward(self,x,y):\n        l1 = len(x)\n        l = len(x[0])\n        s = ((-1)*sum(y[0]*torch.log(x[0]) + (1-y[0])*(torch.log(1-x[0])))/l).clone()\n        for X,Y in zip(x,y):\n            s += ((-1)*sum(Y*torch.log(X) + (1-Y)*(torch.log(1-X)))/l).clone()\n        s = s/l1\n        return s\na = myloss()\na([torch.tensor([.3,.3,.3]),torch.tensor([.3,.3,.3])],[torch.tensor([0,0,1]),torch.tensor([0,0,1])])'

In [84]:
from torch import nn

class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork,self).__init__()
        self.seq_modules = nn.Sequential(
            nn.Linear(75,100),
            nn.BatchNorm1d(num_features = 100),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(100,45),
            nn.BatchNorm1d(num_features = 45),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(45,9),
            nn.ReLU()
        )
    def forward(self,x):
        logits = self.seq_modules(x)
        return logits


model = NeuralNetwork()


loss_fn = nn.CrossEntropyLoss()
#pred = model(next(iter(train_dataloader)))
#pred, pred.argmax(0)

In [85]:
for x in model.parameters():
    x = x.multiply(100)
    print(x)

tensor([[  6.3639,   9.2108,  -0.7271,  ...,   7.7133,  -5.9643,   2.0096],
        [-11.4032,  -0.3456,  -1.9172,  ...,   1.8718,  -9.4891,  -0.7950],
        [ -8.1252,  -2.5892,  -0.0675,  ..., -10.4712,   2.9093,   0.9734],
        ...,
        [  3.2701,   9.4112,  -0.8646,  ...,   4.4504,   1.9496,  10.5874],
        [ -6.6690,  -0.2522,  -3.2076,  ..., -11.4013,  -5.2081,  -5.7904],
        [ -8.1135,   8.6788,   1.0343,  ...,   9.3495,   3.5315,   4.0280]],
       grad_fn=<MulBackward1>)
tensor([  8.0487,  -8.2219,   7.2746,  -0.6441,  10.0946,  11.1216,  -7.7319,
          7.7818,   7.7496,  -0.4476,  -9.5909,   1.5685,  -7.3043,  11.1588,
         -3.3742,  -5.8377,  -3.0987,  -8.4508,   7.6702,   1.4493,  -3.0463,
         -8.3037,  -7.3122,   6.8028,  -1.1427,   2.5066,  -5.0382,   9.8125,
         -5.8034,  -0.6905,   8.0432,  -9.6876,  -6.8563, -10.8590,   2.0620,
         -6.6833, -10.3072,   4.1408,  -7.1085,  -0.6839,   2.7290,  -5.1677,
         -5.7561,  -1.6961,   4

In [86]:
def train_loop(dataloader, model, loss_fn, optimiser):
    size = len(dataloader.dataset)
    correct = 0
    for batch, (X,y) in enumerate(dataloader):
        pred = model(X)
        loss = loss_fn(pred, y)
        
        optimiser.zero_grad()
        loss.backward()
        optimiser.step()
        correct += ((nn.functional.softmax(pred)).argmax(1) == y).type(torch.float).sum().item()
        
        if (batch+1)%200 == 0 :
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}], accuracy = {correct*100/current}")
def test_loop(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    test_loss, correct = 0, 0

    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += ((nn.functional.softmax(pred)).argmax(1) == y).type(torch.float).sum().item()
            
    test_loss /= size
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [89]:
batch_s = 50
epochs = 100
lr_rate = .000005

optimiser = torch.optim.Adam(model.parameters(),lr = lr_rate)
for t in range(epochs):
    train_dataloader = DataLoader(training_data, batch_size = batch_s, shuffle = True)
    test_dataloader = DataLoader(testing_data, batch_size = batch_s, shuffle = True)
    print(f"Epoch {t+1}\n-------------------------------")
    train_loop(train_dataloader, model, loss_fn, optimiser)
    test_loop(test_dataloader, model, loss_fn)
    print(f"Learning Rate : {lr_rate}")
print("Done!")

Epoch 1
-------------------------------


<ipython-input-86-f161d4b08ec4>:11: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  correct += ((nn.functional.softmax(pred)).argmax(1) == y).type(torch.float).sum().item()


loss: 1.704190  [ 9950/160000], accuracy = 36.11055276381909
loss: 1.567688  [19950/160000], accuracy = 35.45363408521303
loss: 1.841494  [29950/160000], accuracy = 35.62938230383973
loss: 1.807764  [39950/160000], accuracy = 35.677096370463076
loss: 1.937318  [49950/160000], accuracy = 35.68368368368368
loss: 1.473621  [59950/160000], accuracy = 35.7581317764804
loss: 1.670188  [69950/160000], accuracy = 35.64974982130093
loss: 1.835750  [79950/160000], accuracy = 35.55222013758599
loss: 1.594219  [89950/160000], accuracy = 35.52973874374653
loss: 1.780905  [99950/160000], accuracy = 35.49874937468734
loss: 1.601875  [109950/160000], accuracy = 35.47794452023647
loss: 1.602077  [119950/160000], accuracy = 35.485619007919965
loss: 1.850824  [129950/160000], accuracy = 35.455944594074644
loss: 1.681271  [139950/160000], accuracy = 35.464094319399784
loss: 1.775392  [149950/160000], accuracy = 35.451150383461155
loss: 1.733500  [159950/160000], accuracy = 35.43232260081275


<ipython-input-86-f161d4b08ec4>:24: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  correct += ((nn.functional.softmax(pred)).argmax(1) == y).type(torch.float).sum().item()


Test Error: 
 Accuracy: 34.9%, Avg loss: 0.035684 

Learning Rate : 5e-06
Epoch 2
-------------------------------
loss: 1.727819  [ 9950/160000], accuracy = 36.33165829145729
loss: 1.531716  [19950/160000], accuracy = 36.34586466165413
loss: 1.844967  [29950/160000], accuracy = 36.0567612687813
loss: 1.693398  [39950/160000], accuracy = 36.05006257822278
loss: 1.693697  [49950/160000], accuracy = 35.9019019019019
loss: 1.780951  [59950/160000], accuracy = 35.83819849874896
loss: 1.839656  [69950/160000], accuracy = 35.7855611150822
loss: 1.710618  [79950/160000], accuracy = 35.67729831144465
loss: 1.775517  [89950/160000], accuracy = 35.662034463590885
loss: 1.969712  [99950/160000], accuracy = 35.656828414207105
loss: 1.521127  [109950/160000], accuracy = 35.598908594815825
loss: 1.754414  [119950/160000], accuracy = 35.582325969153814
loss: 1.551610  [129950/160000], accuracy = 35.57983839938438
loss: 1.799732  [139950/160000], accuracy = 35.591282600928906
loss: 1.620532  [149950/16

loss: 1.626086  [79950/160000], accuracy = 35.31957473420888
loss: 1.819114  [89950/160000], accuracy = 35.33629794330184
loss: 1.970541  [99950/160000], accuracy = 35.31865932966483
loss: 1.837649  [109950/160000], accuracy = 35.32514779445202
loss: 1.741786  [119950/160000], accuracy = 35.38557732388495
loss: 1.684084  [129950/160000], accuracy = 35.41362062331666
loss: 1.781627  [139950/160000], accuracy = 35.45051804215792
loss: 1.634958  [149950/160000], accuracy = 35.56852284094698
loss: 1.807820  [159950/160000], accuracy = 35.53610503282276
Test Error: 
 Accuracy: 35.0%, Avg loss: 0.035676 

Learning Rate : 5e-06
Epoch 10
-------------------------------
loss: 1.791749  [ 9950/160000], accuracy = 36.2713567839196
loss: 1.779868  [19950/160000], accuracy = 35.68421052631579
loss: 1.694199  [29950/160000], accuracy = 35.86644407345576
loss: 1.636151  [39950/160000], accuracy = 35.58698372966208
loss: 1.746919  [49950/160000], accuracy = 35.64364364364364
loss: 1.783973  [59950/160

Test Error: 
 Accuracy: 35.1%, Avg loss: 0.035684 

Learning Rate : 5e-06
Epoch 17
-------------------------------
loss: 1.682165  [ 9950/160000], accuracy = 34.97487437185929
loss: 1.756493  [19950/160000], accuracy = 35.38345864661654
loss: 1.895227  [29950/160000], accuracy = 35.66277128547579
loss: 1.820133  [39950/160000], accuracy = 35.61952440550689
loss: 2.034138  [49950/160000], accuracy = 35.5055055055055
loss: 1.752428  [59950/160000], accuracy = 35.59799833194329
loss: 1.704688  [69950/160000], accuracy = 35.572551822730524
loss: 1.513152  [79950/160000], accuracy = 35.54471544715447
loss: 1.712888  [89950/160000], accuracy = 35.47192884936076
loss: 1.859655  [99950/160000], accuracy = 35.509754877438716
loss: 1.594464  [109950/160000], accuracy = 35.49522510231924
loss: 1.832587  [119950/160000], accuracy = 35.49895789912463
loss: 1.976356  [129950/160000], accuracy = 35.472104655636784
loss: 1.799374  [139950/160000], accuracy = 35.47552697391926
loss: 1.659716  [149950/1

loss: 1.810184  [79950/160000], accuracy = 35.46966854283927
loss: 1.898292  [89950/160000], accuracy = 35.488604780433576
loss: 1.646261  [99950/160000], accuracy = 35.398699349674835
loss: 1.582893  [109950/160000], accuracy = 35.4924965893588
loss: 1.870500  [119950/160000], accuracy = 35.530637765735726
loss: 1.544388  [129950/160000], accuracy = 35.54290111581378
loss: 1.803315  [139950/160000], accuracy = 35.47338335119686
loss: 1.718242  [149950/160000], accuracy = 35.52117372457486
loss: 1.699615  [159950/160000], accuracy = 35.521100343857455
Test Error: 
 Accuracy: 34.9%, Avg loss: 0.035681 

Learning Rate : 5e-06
Epoch 25
-------------------------------
loss: 1.698917  [ 9950/160000], accuracy = 35.19597989949749
loss: 1.568867  [19950/160000], accuracy = 35.62406015037594
loss: 1.920637  [29950/160000], accuracy = 35.419031719532555
loss: 1.760020  [39950/160000], accuracy = 35.35419274092616
loss: 1.581004  [49950/160000], accuracy = 35.331331331331334
loss: 1.736977  [599

loss: 1.692943  [159950/160000], accuracy = 35.40418880900281
Test Error: 
 Accuracy: 34.8%, Avg loss: 0.035705 

Learning Rate : 5e-06
Epoch 32
-------------------------------
loss: 1.770061  [ 9950/160000], accuracy = 34.85427135678392
loss: 1.695210  [19950/160000], accuracy = 35.12280701754386
loss: 1.862180  [29950/160000], accuracy = 35.45909849749582
loss: 1.696589  [39950/160000], accuracy = 35.26658322903629
loss: 1.680952  [49950/160000], accuracy = 35.331331331331334
loss: 1.705691  [59950/160000], accuracy = 35.436196830692246
loss: 1.741928  [69950/160000], accuracy = 35.42816297355254
loss: 1.673303  [79950/160000], accuracy = 35.41338336460288
loss: 1.862987  [89950/160000], accuracy = 35.3485269594219
loss: 1.707020  [99950/160000], accuracy = 35.38569284642321
loss: 1.817741  [109950/160000], accuracy = 35.39699863574352
loss: 1.826148  [119950/160000], accuracy = 35.411421425594
loss: 1.802466  [129950/160000], accuracy = 35.39746056175452
loss: 1.707281  [139950/1600

KeyboardInterrupt: 

In [41]:
for x in model.parameters():
    print(x)

Parameter containing:
tensor([[-0.0636,  0.0257,  0.0445,  ...,  0.0568, -0.0705, -0.2476],
        [-0.1350, -0.1646,  0.0975,  ...,  0.0253, -0.0586, -0.1283],
        [-0.1585,  0.0409, -0.0578,  ..., -0.0105, -0.0284, -0.3159],
        ...,
        [ 0.1652,  0.0161,  0.1442,  ...,  0.0458,  0.1042, -0.0191],
        [-0.0249,  0.0840, -0.0194,  ..., -0.2623, -0.0562,  0.0081],
        [-0.0311,  0.1194,  0.0779,  ...,  0.0420,  0.1219,  0.1521]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0787,  0.1124, -0.1677, -0.0472,  0.0481,  0.0206,  0.0930, -0.1266,
         0.0594, -0.0311, -0.0950,  0.0086,  0.0499, -0.1312,  0.0484,  0.0176,
         0.0134, -0.0595, -0.0285,  0.0201, -0.0546,  0.0883, -0.0740, -0.0492,
         0.0726,  0.1203, -0.1046,  0.0451,  0.0257, -0.0889,  0.1119, -0.1380,
        -0.0341,  0.0121, -0.0396,  0.0386,  0.1075, -0.0140, -0.1292,  0.0869,
         0.1160, -0.1591,  0.0618,  0.1205,  0.0570], requires_grad=True)
Parameter containing:

In [232]:
for x in model.parameters():
    print(x)

Parameter containing:
tensor([[ 0.0770, -0.0173, -0.1597,  ..., -0.0882,  0.0048, -0.0555],
        [-0.1017, -0.0651,  0.0326,  ...,  0.1380,  0.0145,  0.0595],
        [ 0.0231,  0.0080, -0.1274,  ..., -0.1418,  0.0490,  0.0231],
        ...,
        [ 0.0228,  0.0200,  0.0304,  ...,  0.0826, -0.0594, -0.0407],
        [ 0.0520, -0.0925,  0.0698,  ..., -0.0761, -0.0641,  0.1288],
        [-0.1009, -0.0551, -0.0063,  ...,  0.0579, -0.0042, -0.0124]],
       requires_grad=True)
Parameter containing:
tensor([-1.0025e-01, -1.0308e-01,  1.0954e-01, -1.3122e-02,  4.3177e-02,
         7.3575e-02,  4.3837e-02, -1.5967e-01,  1.8187e-01,  2.3326e-01,
        -4.3246e-02, -1.1289e-01,  5.8449e-02, -1.2110e-01,  5.7925e-02,
        -1.5396e-01, -1.3163e-01,  1.6708e-01, -1.2788e-01,  1.3268e-02,
         1.0140e-01,  3.4252e-01,  1.5024e-01, -3.9175e-02, -1.3434e-01,
        -3.1853e-01,  1.5481e-01,  2.7301e-01,  2.3915e-01, -4.4431e-02,
        -4.2798e-02,  1.2929e-01,  3.6477e-02, -2.2467e-0

In [150]:
len(next(iter(train_dataloader))[0][0])

75

In [90]:
y = nn.functional.softmax(model(torch.tensor(datt1.values.astype(np.float32))),dim=1)

In [91]:
y.size()

torch.Size([100000, 9])

In [92]:
sub = pd.DataFrame(y.detach().numpy())

In [93]:
lis = [f"Class_{i}" for i in range(1,10)]
sub.columns = lis
sub.head()

Class_1   Class_2   Class_3   Class_4   Class_5   Class_6   Class_7  \
0  0.054657  0.307126  0.140176  0.021094  0.021094  0.213183  0.032939   
1  0.041360  0.126510  0.084928  0.025120  0.025120  0.219802  0.074822   
2  0.032708  0.040827  0.034627  0.006995  0.006995  0.517231  0.053770   
3  0.042343  0.091037  0.065261  0.016633  0.016633  0.322088  0.070627   
4  0.050013  0.130166  0.086135  0.023270  0.023270  0.262936  0.068375   

    Class_8   Class_9  
0  0.074276  0.135455  
1  0.258397  0.143942  
2  0.221040  0.085806  
3  0.240461  0.134917  
4  0.209804  0.146031

In [94]:
sub1 = pd.concat([iden,sub],axis = 1)
sub1.head()

id   Class_1   Class_2   Class_3   Class_4   Class_5   Class_6  \
0  200000  0.054657  0.307126  0.140176  0.021094  0.021094  0.213183   
1  200001  0.041360  0.126510  0.084928  0.025120  0.025120  0.219802   
2  200002  0.032708  0.040827  0.034627  0.006995  0.006995  0.517231   
3  200003  0.042343  0.091037  0.065261  0.016633  0.016633  0.322088   
4  200004  0.050013  0.130166  0.086135  0.023270  0.023270  0.262936   

    Class_7   Class_8   Class_9  
0  0.032939  0.074276  0.135455  
1  0.074822  0.258397  0.143942  
2  0.053770  0.221040  0.085806  
3  0.070627  0.240461  0.134917  
4  0.068375  0.209804  0.146031

In [95]:
for i in range(1,10):
    sub1[f"Class_{i}"] = sub1[f"Class_{i}"].round(decimals = 4)
sub1.head()

id  Class_1  Class_2  Class_3  Class_4  Class_5  Class_6  Class_7  \
0  200000   0.0547   0.3071   0.1402   0.0211   0.0211   0.2132   0.0329   
1  200001   0.0414   0.1265   0.0849   0.0251   0.0251   0.2198   0.0748   
2  200002   0.0327   0.0408   0.0346   0.0070   0.0070   0.5172   0.0538   
3  200003   0.0423   0.0910   0.0653   0.0166   0.0166   0.3221   0.0706   
4  200004   0.0500   0.1302   0.0861   0.0233   0.0233   0.2629   0.0684   

   Class_8  Class_9  
0   0.0743   0.1355  
1   0.2584   0.1439  
2   0.2210   0.0858  
3   0.2405   0.1349  
4   0.2098   0.1460

In [96]:
sub1.to_csv('submission4.csv',index = False,header = True)